name: Create Terraform Remote State

on: 
  push:
    branches: [dev]
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./

permissions: read-all

jobs:

  deploy-azure-infra-terraform:
    name: Deploy to Azure with Terraform
    runs-on: ubuntu-latest
    permissions: write-all
    environment: Development

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Login to Azure with OIDC
      - name: Azure login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create Terraform backend state storage
        uses: Azure/cli@v2.1.0
        with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          inlineScript: |
            az account show

            echo "ðŸŽ¯ Setting default subscription for: " ${{ secrets.SUBSCRIPTION_ID }}
            az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}

            echo "ðŸŽ¯ Getting resource group named: " ${{ vars.RESOURCE_GROUP_NAME }}
            RG_EXISTS=$(az group exists --name ${{ vars.RESOURCE_GROUP_NAME }} )
            if [ $RG_EXISTS == "false" ]; then
              echo "Resource group not found, creating... "
              az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.LOCATION }}
            fi
            RESOURCE_GROUP_ID=$(az group show -n ${{ vars.RESOURCE_GROUP_NAME }} -o tsv --query id)

            echo "ðŸŽ¯ Getting storage account named: " ${{ vars.STORAGE_ACCOUNT_NAME }}
            STORAGE_ACCOUNT_NOT_FOUND=$(az storage account check-name --name ${{ vars.STORAGE_ACCOUNT_NAME }}  --query nameAvailable)
            if [ $STORAGE_ACCOUNT_NOT_FOUND == "true" ]; then
              echo ""
              echo "Storage account not found. Creating..."
              az storage account create --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name ${{ vars.STORAGE_ACCOUNT_NAME }}  --sku Standard_LRS --encryption-services blob
            fi
            STORAGE_ACCOUNT=$(az storage account show --name ${{ vars.STORAGE_ACCOUNT_NAME }} -o tsv --query id)

            echo "ðŸŽ¯ Getting storage account container named: " ${{ vars.CONTAINER_NAME }}
            STORAGE_COUNTAINER_EXISTS=$(az storage container exists --name ${{ vars.CONTAINER_NAME }} --account-name ${{ vars.STORAGE_ACCOUNT_NAME }}  --query exists)
            if [ $STORAGE_COUNTAINER_EXISTS == "false" ]; then
              echo ""
              echo "Blob container not found. Creating..."
              az storage container create --name ${{ vars.CONTAINER_NAME }} --account-name ${{ vars.STORAGE_ACCOUNT_NAME }}
            fi
            STORAGE_CONTAINER=$(az storage account show --name ${{ vars.STORAGE_ACCOUNT_NAME }} -o tsv --query primaryEndpoints.blob)${{ vars.CONTAINER_NAME }}

            echo "ðŸŽ¯ Getting storage account key..."
            STORAGE_ACCOUNT_KEY=$(az storage account keys list --resource-group ${{ vars.RESOURCE_GROUP_NAME }}  --account-name ${{ vars.STORAGE_ACCOUNT_NAME }} --query "[0].value" -o tsv)
            echo $STORAGE_ACCOUNT_KEY

            echo "ðŸŽ¯ Getting storage connection string..."
            STORAGE_ACCOUNT_CONNECTION_STRING=$(az storage account show-connection-string --resource-group ${{ vars.RESOURCE_GROUP_NAME }}  --name ${{ vars.STORAGE_ACCOUNT_NAME }} --query "connectionString"  -o tsv)
            echo $STORAGE_ACCOUNT_CONNECTION_STRING

            echo "ðŸŽ¯ Getting storage blob named: " ${{ vars.BLOB_NAME }}
            STORAGE_BLOB_EXISTS=$(az storage blob exists --name ${{ vars.BLOB_NAME }} --account-name ${{ vars.STORAGE_ACCOUNT_NAME }}  --query exists)
            if [ $STORAGE_BLOB_EXISTS == "false" ]; then
              echo ""
              echo "Storage blob not found. Creating..."

            # generate backend.tf file
            cd ${{ env.WORKING_DIRECTOR }}
            cat <<EOT > terraform.tfstate
            terraform {
              backend "azurerm" {
                resource_group_name   = "${{ vars.RESOURCE_GROUP_NAME }}"
                storage_account_name  = "${{ vars.STORAGE_ACCOUNT_NAME }}"
                container_name        = "${{ vars.CONTAINER_NAME }}"
                key                   = "${{ vars.BLOB_NAME }}"
              }
            }
            EOT

            cat terraform.tfstate

